# Generated by Django 4.1.4 on 2023-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='gjk', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
